# Generated by Django 5.0.6 on 2024-05-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='название категорий')),
                ('category_description', models.TextField(blank=True, null=True, verbose_name='описание категорий')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование продукта')),
                ('product_description', models.CharField(max_length=100, verbose_name='описание продукта')),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='изображение продукта')),
                ('product_price', models.IntegerField(verbose_name='цена продукта')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления записи')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('product_name',),
            },
        ),
    ]
