# Generated by Django 5.0.6 on 2024-06-14 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_version",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="версия номера"
                    ),
                ),
                (
                    "version_name",
                    models.CharField(max_length=150, verbose_name="название версий"),
                ),
                (
                    "is_current",
                    models.BooleanField(default=False, verbose_name="признак версий"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="catalog.product",
                        verbose_name="Версия",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия",
                "verbose_name_plural": "версий",
            },
        ),
    ]
