# Generated by Django 4.2.2 on 2024-06-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("product_name",),
                "permissions": [
                    ("can_update_category", "Can update category"),
                    ("can_remove_publish", "Can remove publish"),
                    ("can_update_description", "Can update description"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publish",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Статус продукта"
            ),
        ),
    ]
